name: drizzle-effect

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    command: ["--max_connections=1000"]
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 45s
      interval: 5s
      retries: 10

  pscale:
    image: ghcr.io/mattrobenolt/ps-http-sim:latest
    command:
      [
        "-listen-port=3900",
        "-mysql-dbname=db",
        "-mysql-addr=mysql",
        "-mysql-max-rows=100000",
        "-mysql-idle-timeout=1s",
      ]
    ports:
      - "3900:3900"
    depends_on:
      - mysql

volumes:
  mysql:
